create table if not exists payroll_bonuses (
    id            bigint generated by default as identity primary key,
    employee_id   bigint         not null references employees (id),
    bonus_type    varchar(30)    not null,
    ref_year      integer        not null,
    reference_id  bigint         not null default 0,
    amount        numeric(14, 2) not null default 0,
    status        varchar(20)    not null default 'PAID',
    payment_date  date,
    created_at    timestamp      not null,
    updated_at    timestamp,
    created_by    varchar(255),
    constraint uq_payroll_bonus unique (employee_id, bonus_type, ref_year, reference_id)
);
