-- Encomenda a fornecedor (purchase order). Não move stock até à recepção.
create table if not exists purchase_orders (
    id                  bigint generated by default as identity primary key,
    order_number        varchar(60)   not null unique,
    supplier_id         bigint        not null references suppliers (id),
    company_id          bigint        not null references companies (id),
    warehouse_id        bigint        not null references warehouses (id),
    expected_date       date,
    order_date          timestamp     not null,
    received_at         timestamp,
    total_amount        numeric(18, 2) not null default 0,
    tax_amount          numeric(18, 2) not null default 0,
    status              varchar(20)   not null default 'ORDERED',
    notes               varchar(500),
    cancellation_reason varchar(500),
    created_at          timestamp     not null,
    updated_at          timestamp,
    created_by          varchar(255)
);

create table if not exists purchase_order_lines (
    id                bigint generated by default as identity primary key,
    purchase_order_id bigint        not null references purchase_orders (id),
    product_id        bigint        not null references products (id),
    quantity          numeric(18, 3) not null,
    unit_price        numeric(18, 2) not null,
    tax_rate          numeric(5, 4)  not null,
    line_total        numeric(18, 2) not null,
    batch_number      varchar(120),
    expiration_date   date,
    serial_number     varchar(120)
);

create index if not exists idx_po_company_status on purchase_orders (company_id, status);
create index if not exists idx_pol_order on purchase_order_lines (purchase_order_id);
