-- Configuração de colunas dos documentos passa a ser POR TIPO de documento (COMMERCIAL vs
-- POS_RECEIPT), com config independente por empresa, mais um comentário/rodapé para o recibo.
-- Recria a tabela (a config anterior é preferência visual, sem impacto de dados) para trocar o
-- unique de (company_id) para (company_id, document_type) de forma portável (H2 + PostgreSQL).
drop table if exists document_column_config;

create table document_column_config (
    id               bigint generated by default as identity primary key,
    company_id       bigint      not null,
    document_type    varchar(20) not null default 'COMMERCIAL',
    show_barcode     boolean     not null default true,
    show_reference   boolean     not null default true,
    show_description boolean     not null default true,
    show_expiry      boolean     not null default true,
    show_quantity    boolean     not null default true,
    show_unit_price  boolean     not null default true,
    show_tax         boolean     not null default true,
    show_subtotal    boolean     not null default true,
    footer_comment   varchar(255),
    created_at       timestamp   not null,
    updated_at       timestamp,
    created_by       varchar(255),
    constraint uk_doc_col_company_type unique (company_id, document_type)
);
