-- Assinaturas por empresa (1:1) e pagamentos manuais registados pelo superadmin.
-- Empresas existentes ficam sem assinatura (login continua a ser gerido por companies.active);
-- uma assinatura EXPIRED/SUSPENDED passa a bloquear o login dessa empresa.
create table subscriptions (
    id            bigint generated by default as identity primary key,
    company_id    bigint       not null unique,
    plan          varchar(20)  not null default 'TRIAL',
    status        varchar(20)  not null default 'TRIAL',
    start_date    date,
    valid_until   date,
    monthly_price numeric(19,2) not null default 0,
    created_at    timestamp    not null,
    updated_at    timestamp,
    created_by    varchar(255)
);

create table subscription_payments (
    id           bigint generated by default as identity primary key,
    company_id   bigint        not null,
    amount       numeric(19,2) not null,
    method       varchar(20)   not null,
    paid_at      date          not null,
    period_start date,
    period_end   date,
    note         varchar(255),
    created_at   timestamp     not null,
    updated_at   timestamp,
    created_by   varchar(255)
);

create index idx_sub_payment_company on subscription_payments (company_id);
