-- Assistência: tickets abertos por uma empresa e tratados pelo superadmin, com conversa (mensagens).
-- Distinto do módulo `crm` (assistência ao cliente da empresa) — aqui a empresa é o cliente da plataforma.
create table support_tickets (
    id          bigint generated by default as identity primary key,
    company_id  bigint       not null,
    subject     varchar(255) not null,
    description varchar(2000),
    status      varchar(20)  not null default 'OPEN',
    priority    varchar(20)  not null default 'NORMAL',
    assignee    varchar(255),
    created_at  timestamp    not null,
    updated_at  timestamp,
    created_by  varchar(255)
);

create table support_messages (
    id               bigint generated by default as identity primary key,
    ticket_id        bigint        not null,
    author           varchar(255)  not null,
    from_super_admin boolean       not null default false,
    body             varchar(2000) not null,
    created_at       timestamp     not null,
    updated_at       timestamp,
    created_by       varchar(255)
);

create index idx_support_ticket_company on support_tickets (company_id);
create index idx_support_message_ticket on support_messages (ticket_id);
