-- Sessão de contagem de inventário persistente (contagem cega + reconciliação).
-- Permite guardar a contagem, retomar mais tarde e aplicar os ajustes por etapas, com histórico
-- auditável (sistema -> contado por artigo). Complementa a folha de contagem e o ajuste de stock.

create table if not exists inventory_counts (
    id           bigint       generated by default as identity primary key,
    company_id   bigint       not null references companies (id),
    warehouse_id bigint       not null references warehouses (id),
    status       varchar(20)  not null default 'DRAFT',
    note         varchar(500),
    applied_at   timestamp,
    applied_by   varchar(255),
    created_at   timestamp    not null,
    updated_at   timestamp,
    created_by   varchar(255)
);

create table if not exists inventory_count_lines (
    id                 bigint         generated by default as identity primary key,
    inventory_count_id bigint         not null references inventory_counts (id),
    product_id         bigint         not null references products (id),
    counted_quantity   numeric(18, 3),
    system_quantity    numeric(18, 3),
    applied            boolean        not null default false
);

create index if not exists idx_invcount_company_status on inventory_counts (company_id, status);
create index if not exists idx_invcountline_count on inventory_count_lines (inventory_count_id);
