-- Guia de Remessa ao cliente, gerada a partir de uma encomenda (série GR).
-- Documento que acompanha a mercadoria expedida; dá saída ao stock (SALE) só na aprovação.
-- Caminhos separados: uma encomenda vira guia OU fatura, nunca as duas. Ver
-- docs/GUIA_REMESSA_ENCOMENDA_SPEC.md.
--
-- Numeração por empresa: UNIQUE(company_id, guide_number) — nunca UNIQUE global no número
-- (lição da V31, para não colidir entre empresas com o mesmo GR-2026/N).

create table if not exists delivery_guides (
    id               bigint        generated by default as identity primary key,
    guide_number     varchar(255)  not null,
    guide_date       timestamp     not null,
    company_id       bigint        not null references companies (id),
    order_id         bigint        not null references customer_orders (id),
    order_number     varchar(255),
    client_id        bigint        not null references clients (id),
    walk_in_name     varchar(120),
    warehouse_id     bigint        not null references warehouses (id),
    total_amount     numeric(18, 2) not null default 0,
    status           varchar(20)   not null default 'PENDING_APPROVAL',
    responsible      varchar(120),
    vehicle          varchar(120),
    notes            varchar(500),
    approved_by      varchar(80),
    approved_at      timestamp,
    rejection_reason varchar(500),
    created_at       timestamp     not null,
    updated_at       timestamp,
    created_by       varchar(255),
    constraint uk_delivery_guides_company_number unique (company_id, guide_number)
);

create table if not exists delivery_guide_lines (
    id                  bigint         generated by default as identity primary key,
    guide_id            bigint         not null references delivery_guides (id),
    product_id          bigint         not null references products (id),
    quantity            numeric(12, 3) not null,
    unit_price          numeric(18, 2) not null,
    tax_rate            numeric(5, 4)  not null,
    discount_percentage numeric(5, 2),
    line_total          numeric(18, 2) not null,
    batch_number        varchar(255),
    serial_number       varchar(255)
);

create index if not exists idx_delivery_guides_company_status on delivery_guides (company_id, status);
create index if not exists idx_delivery_guide_lines_guide on delivery_guide_lines (guide_id);

-- Ligação (traçabilidade) da encomenda à sua guia activa. Coluna simples, como customer_orders.invoice_id.
alter table customer_orders add column if not exists delivery_guide_id bigint;
