-- Que versão do programa cada empresa está a usar.
--
-- Porquê: antes de subir app.client.min-version é preciso saber quem fica bloqueado. Sem esta
-- tabela a decisão era às cegas — podia-se trancar lojas sem sequer saber que existiam nessa
-- versão. Ver docs/ACTUALIZACOES_CLIENTE_SPEC.md §8.
--
-- Uma linha por (empresa, versão): é uma fotografia de quem está em quê, não um histórico de
-- acessos. O serviço só grava de 15 em 15 minutos por chave — uma loja faz milhares de pedidos
-- por dia e a versão dela muda uma vez por mês.
create table if not exists client_version_sightings (
    id             bigint      generated by default as identity primary key,
    company_id     bigint      not null references companies (id),
    client_version varchar(40) not null,
    last_username  varchar(80),
    first_seen_at  timestamp   not null,
    last_seen_at   timestamp   not null,
    created_at     timestamp   not null,
    updated_at     timestamp,
    created_by     varchar(255),
    constraint uk_client_version_company_version unique (company_id, client_version)
);

create index if not exists idx_client_version_last_seen on client_version_sightings (last_seen_at desc);
