-- Cotação ao cliente (série CT) — a proposta de preço que antecede a encomenda.
-- Não move stock, dívida, caixa nem contabilidade: o compromisso nasce na conversão em encomenda.
-- Ver docs/COTACAO_SPEC.md.
--
-- Numeração por empresa: UNIQUE(company_id, quotation_number) — nunca UNIQUE global no número
-- (lição da V31, para não colidir entre empresas com o mesmo CT-2026/N).
--
-- Nota sobre a caducidade: não há coluna de estado "expirada". A caducidade é derivada de
-- valid_until contra a data de hoje (Quotation.isExpired). Gravá-la exigiria um agendador
-- nocturno e deixaria linhas desactualizadas entre passagens. Ver spec §4.

create table if not exists quotations (
    id                bigint         generated by default as identity primary key,
    quotation_number  varchar(255)   not null,
    quotation_date    timestamp      not null,
    valid_until       date           not null,
    company_id        bigint         not null references companies (id),
    client_id         bigint         not null references clients (id),
    walk_in_name      varchar(120),
    warehouse_id      bigint         not null references warehouses (id),
    total_before_tax  numeric(18, 2) not null default 0,
    tax_amount        numeric(18, 2) not null default 0,
    total_amount      numeric(18, 2) not null default 0,
    status            varchar(20)    not null default 'DRAFT',
    payment_terms     varchar(200),
    delivery_terms    varchar(200),
    -- Prazo de entrega em DIAS a contar da confirmação. Não é data porque a cotação não sabe
    -- quando o cliente vai confirmar — a data nasce na conversão (ver ENCOMENDA_PROFISSIONAL_SPEC).
    delivery_days     integer,
    notes             varchar(1000),
    sent_at           timestamp,
    decided_at        timestamp,
    decided_by        varchar(80),
    rejection_reason  varchar(500),
    order_id          bigint,
    order_number      varchar(255),
    version           bigint         not null default 0,
    created_at        timestamp      not null,
    updated_at        timestamp,
    created_by        varchar(255),
    constraint uk_quotations_company_number unique (company_id, quotation_number)
);

create table if not exists quotation_lines (
    id                  bigint         generated by default as identity primary key,
    quotation_id        bigint         not null references quotations (id),
    product_id          bigint         not null references products (id),
    quantity            numeric(12, 3) not null,
    unit_price          numeric(18, 2) not null,
    tax_rate            numeric(5, 4)  not null,
    discount_percentage numeric(5, 2),
    line_total          numeric(18, 2) not null
);

create index if not exists idx_quotations_company_status on quotations (company_id, status);
-- Quem abre o ecrã pergunta sempre "o que é que está a caducar?".
create index if not exists idx_quotations_company_valid_until on quotations (company_id, valid_until);
create index if not exists idx_quotation_lines_quotation on quotation_lines (quotation_id);
