ALTER TABLE clients
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE products
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE suppliers
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
