create table if not exists promotions (
    id            bigint generated by default as identity primary key,
    company_id    bigint        not null references companies (id),
    name          varchar(255)  not null,
    type          varchar(20)   not null,
    product_id    bigint        references products (id),
    category_id   bigint        references product_categories (id),
    percent_value numeric(5, 2),
    buy_quantity  integer,
    pay_quantity  integer,
    start_date    date          not null,
    end_date      date          not null,
    active        boolean       not null default true,
    created_at    timestamp     not null,
    updated_at    timestamp,
    created_by    varchar(255)
);

create index if not exists idx_promo_company_active on promotions (company_id, active);
