-- Configuração (por empresa) das colunas visíveis na tabela de linhas dos documentos comerciais
-- (fatura, encomenda, nota de crédito, guia). Uma linha por empresa; ausência = todas visíveis.
create table if not exists document_column_config (
    id               bigint generated by default as identity primary key,
    company_id       bigint      not null unique,
    show_barcode     boolean     not null default true,
    show_reference   boolean     not null default true,
    show_description boolean     not null default true,
    show_expiry      boolean     not null default true,
    show_quantity    boolean     not null default true,
    show_unit_price  boolean     not null default true,
    show_tax         boolean     not null default true,
    show_subtotal    boolean     not null default true,
    created_at       timestamp   not null,
    updated_at       timestamp,
    created_by       varchar(255)
);
