-- Contabilidade: plano de contas (PGC-NIRF) + diário de partidas dobradas.
--
-- Porquê: era a maior ausência para um ERP de gestão — o sistema registava vendas, compras,
-- caixa e salários mas não tinha razão, plano de contas nem balancete, pelo que nada disto
-- chegava a ser contabilidade. Ver docs/CONTABILIDADE_SPEC.md.
--
-- Multi-empresa em tudo: plano por empresa e numeração LC por empresa (lição da V31 — nunca
-- UNIQUE global num número de documento).

create table if not exists accounts (
    id            bigint       generated by default as identity primary key,
    code          varchar(20)  not null,
    name          varchar(200) not null,
    company_id    bigint       not null references companies (id),
    account_class varchar(40)  not null,
    nature        varchar(10)  not null,
    postable      boolean      not null default true,
    active        boolean      not null default true,
    parent_code   varchar(20),
    created_at    timestamp    not null,
    updated_at    timestamp,
    created_by    varchar(255),
    constraint uk_accounts_company_code unique (company_id, code)
);

create index if not exists idx_accounts_company on accounts (company_id);

create table if not exists journal_entries (
    id                     bigint       generated by default as identity primary key,
    entry_number           varchar(40)  not null,
    company_id             bigint       not null references companies (id),
    entry_date             date         not null,
    description            varchar(300) not null,
    source                 varchar(30)  not null default 'MANUAL',
    source_document_id     bigint,
    source_document_number varchar(40),
    created_at             timestamp    not null,
    updated_at             timestamp,
    created_by             varchar(255),
    constraint uk_journal_entries_company_number unique (company_id, entry_number)
);

create index if not exists idx_journal_entries_company_date on journal_entries (company_id, entry_date);

-- Um documento só pode dar origem a um lançamento automático: repetir o pedido HTTP não pode
-- duplicar as vendas na contabilidade. Lançamentos manuais têm source_document_id nulo e não
-- são abrangidos (vários ajustes manuais são legítimos).
create unique index if not exists uk_journal_source_document
    on journal_entries (company_id, source, source_document_id)
    where source_document_id is not null;

create table if not exists journal_lines (
    id          bigint         generated by default as identity primary key,
    entry_id    bigint         not null references journal_entries (id) on delete cascade,
    account_id  bigint         not null references accounts (id),
    debit       numeric(16, 2),
    credit      numeric(16, 2),
    description varchar(300)
);

create index if not exists idx_journal_lines_entry on journal_lines (entry_id);
create index if not exists idx_journal_lines_account on journal_lines (account_id);
