alter table customer_orders add column if not exists idempotency_key varchar(100);
alter table customer_orders add column if not exists reservation_active boolean not null default false;
alter table customer_orders add column if not exists version bigint not null default 0;
alter table customer_order_lines add column if not exists reserved_quantity decimal(12,3) not null default 0;
alter table customer_order_lines add column if not exists separated_quantity decimal(12,3) not null default 0;
create unique index if not exists uk_customer_orders_company_idempotency on customer_orders(company_id, idempotency_key);
create table if not exists customer_order_events (
 id bigint generated by default as identity primary key, order_id bigint not null,
 event_type varchar(50) not null, previous_status varchar(40), new_status varchar(40),
 actor_role varchar(30) not null, terminal_name varchar(100), details varchar(1000),
 created_at timestamp not null, updated_at timestamp, created_by varchar(255),
 constraint fk_order_events_order foreign key (order_id) references customer_orders(id));
create index if not exists idx_order_events_order_created on customer_order_events(order_id, created_at);
