-- Conferência à chegada: o que se encomendou ao fornecedor vs o que ele entregou.
--
-- Porquê: pagar 100 e receber 95 não é um roubo grande — são 3 sacos de cada vez, todas as
-- semanas, durante um ano. Sem um registo por ocorrência não há reclamação possível nem forma
-- de saber que fornecedor entrega mal. Ver docs/CONFERENCIA_CHEGADA_SPEC.md.
--
-- Uma linha por ocorrência, não um saldo: a data e a quantidade daquele dia são a prova.
-- Guarda-se o preço unitário da encomenda porque é o valor que se reclama.
create table if not exists goods_receipt_discrepancies (
    id                     bigint         generated by default as identity primary key,
    company_id             bigint         not null references companies (id),
    purchase_order_id      bigint         not null references purchase_orders (id),
    purchase_order_line_id bigint         not null references purchase_order_lines (id),
    product_id             bigint         not null references products (id),
    supplier_id            bigint,
    supplier_name          varchar(200),
    type                   varchar(20)    not null,
    quantity               numeric(14, 3) not null,
    unit_price             numeric(14, 2),
    notes                  varchar(500),
    occurred_on            date           not null,
    resolved               boolean        not null default false,
    resolution_notes       varchar(500),
    created_at             timestamp      not null,
    updated_at             timestamp,
    created_by             varchar(255)
);

create index if not exists idx_grd_company_date on goods_receipt_discrepancies (company_id, occurred_on desc);
create index if not exists idx_grd_supplier on goods_receipt_discrepancies (company_id, supplier_id);
-- O que está por reclamar é a consulta do dia-a-dia.
create index if not exists idx_grd_open on goods_receipt_discrepancies (company_id, resolved);
